### PR TITLE
Updated requirements.txt

### PR DESCRIPTION
**Pull request by safranchik**
Added frozen version of wiser that is used in the reproducibility code

### CODE REVIEW

**Comment by stephenbach** [comment]
Maybe it's best to tag that version of WISER as 0.1?

**Review by stephenbach — CHANGES_REQUESTED** [review]
See comments in conversation.

**Comment by stephenbach** [comment]
Also, we should tag the appropriate version of labelmodels as well.

**Comment by safranchik** [comment]
Just tagged labelmodels and wiser with their corresponding versions. Will update the requirements on the wiser repo soon.

**Review by stephenbach — APPROVED** [review]

**Comment by stephenbach** [comment]
LGTM!

**Pull request merged**
